version: '3.2'
services:
  app:
    image: cccccc/pages-vue:app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '8080:8080'
    volumes:
      - ./:/src
    stdin_open: true
    tty: true